version: "3"
services:
  front:
    container_name: front
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    command: yarn dev

volumes:
  node_modules:
