version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:
  build_and_test:
    docker:
      - image: node:14
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn test
      - run: yarn generate
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - attach_workspace:
          at: ~/project
      - aws-s3/sync:
          from: dist
          to: 's3://pfc-calculator.tk'
      - run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'


workflows:
  build-deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master

# リストアキャッシュでyarn.lockを復元して現在のyarn.lockと変わらないならyarn installを省き、変化してた場合のみyarn installする
# 最後にsave_cacheでyarn.lockをキャッシュして次回のジョブ実行時に差分比較できるようにする

# AWS_ACCESS_KEY_ID, AWS_REGION, AWS_SECRET_ACCESS_KEY, DISTRIBUTION_IDを環境変数として設定する
